package com.jaf.fuzzer.nautilus.exec;

/**
 * Abstraction over the fuzzing target execution that provides coverage feedback. The Nautilus
 * fuzzer invokes this for every generated input.
 */
public interface InstrumentedExecutor {

    /**
     * Executes the target with the provided input.
     *
     * @param input bytes generated by the fuzzer
     * @return execution result containing coverage/crash information
     * @throws Exception when the invocation itself fails (HTTP/network issues, etc.)
     */
    ExecutionResult run(byte[] input) throws Exception;
}
